# Generated by Django 3.1.2 on 2020-11-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0006_2_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stripe_plan', models.ManyToManyField(related_name='features', to='djstripe.Product')),
            ],
        ),
    ]
