# Generated by Django 3.1.2 on 2020-11-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0006_2_3'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresmodel',
            name='stripe_plan',
            field=models.ManyToManyField(blank=True, null=True, related_name='features', to='djstripe.Product'),
        ),
    ]
