# Generated by Django 3.1.2 on 2020-11-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20201110_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuresmodel',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
    ]
