# Generated by Django 3.1.2 on 2021-06-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20201110_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresmodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
