# Generated by Django 3.1.2 on 2021-06-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_featuresmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresmodel',
            name='show_quantity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='featuresmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
