# Generated by Django 3.1.2 on 2021-07-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20210629_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuresmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='featuresmodel',
            name='show_quantity',
        ),
    ]
