# Generated by Django 3.1.2 on 2021-07-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('payments', '0007_auto_20210707_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresmodel',
            name='stripe_product',
            field=models.ManyToManyField(blank=True, related_name='features', to='djstripe.Product'),
        ),
    ]
