# Generated by Django 3.1.2 on 2021-07-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20210707_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresmodel',
            name='stripe_product',
            field=models.ManyToManyField(blank=True, null=True, related_name='features', to='djstripe.Product'),
        ),
    ]
