# Generated by Django 3.1.2 on 2021-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20210707_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresmodel',
            name='stripe_product',
            field=models.ManyToManyField(blank=True, related_name='features', to='djstripe.Product'),
        ),
    ]
