from enum import Enum


class Error(Enum):
    UNKNOWN_ERROR = 100
    NO_RECURSE = 101
    NOT_YOUR_RECURSE = 102
    ALREADY_CREATED = 103
    WARNING = 104
    BANNED_ACCOUNT = 105
    NOT_SUBSCRIBED_ACCOUNT = 106
    HAS_BUILD_IN_PROGRESS = 107
    NOT_AVAILABLE_BUILDS = 108
    CREATE_SUBSCRIPTION_ERROR = 109
    NOT_AVAILABLE_APPS = 110
    BUILD_EXCEPTION = 111
    CREATE_PLAN_ERROR = 112
    UPDATE_PLAN_ERROR = 113
    CREATE_PRICE_ERROR = 114
    ARCHIVE_PRICE_ERROR = 115
    UNARCHIVE_PRICE_ERROR = 116
    NOT_VALID_FEATURE = 117
    CREATE_FEATURE_ERROR = 118
    UPDATE_FEATURE_ERROR = 119
    UPDATE_LIMIT_ERROR = 120
    PAY_INVOICE_ERROR = 121
    PAY_ERROR = 122
    NOT_VALID_STORE = 201
    NOT_VALID_TEMPLATE_URL = 202
    CREATE_TEMPLATE_ERROR = 203
    UPDATE_TEMPLATE_ERROR = 204


class StripeErrorsEn(Enum):
  authentication_required = "The card was declined as the transaction requires authentication."
  approve_with_id = "The payment cannot be authorized."
  call_issuer = "The card has been declined for an unknown reason. Please contact your card issuer for more information."
  card_not_supported = "The card does not support this type of purchase. Please contact your card issuer for more information."
  card_velocity_exceeded = "The customer has exceeded the balance or credit limit available on their card. Please contact your card issuer for more information."
  currency_not_supported = "The card does not support the specified currency."
  do_not_honor = "The card has been declined for an unknown reason. Please contact your card issuer for more information."
  do_not_try_again = "The card has been declined for an unknown reason. Please contact your card issuer for more information."
  duplicate_transaction = "A transaction with identical amount and credit card information was submitted very recently."
  expired_card = "The card has expired."
  fraudulent = "The payment has been declined as Stripe suspects it is fraudulent."
  generic_decline = "The card has been declined for an unknown reason. Please contact your card issuer for more information."
  incorrect_number = "The card number is incorrect."
  incorrect_cvc = "The CVC number is incorrect."
  incorrect_pin = "The PIN entered is incorrect. This decline code only applies to payments made with a card reader."
  incorrect_zip = "The ZIP/postal code is incorrect."
  insufficient_funds = "The card has insufficient funds to complete the purchase."
  invalid_account = "The card, or account the card is connected to, is invalid."
  invalid_amount = "The payment amount is invalid, or exceeds the amount that is allowed."
  invalid_cvc = "The CVC number is incorrect."
  invalid_expiry_month = "The expiration month is invalid."
  invalid_expiry_year = "The expiration year is invalid."
  invalid_number = "The card number is incorrect."
  invalid_pin = "The PIN entered is incorrect. This decline code only applies to payments made with a card reader."
  issuer_not_available = "The card issuer could not be reached, so the payment could not be authorized."
  lost_card = "The payment has been declined because the card is reported lost."
  merchant_blacklist = "The payment has been declined because it matches a value on the Stripe user’s block list."
  new_account_information_available = "The card, or account the card is connected to, is invalid. Please contact your card issuer for more information."
  no_action_taken = "The card has been declined for an unknown reason. Please contact your card issuer for more information."
  not_permitted = "The payment is not permitted. Please contact your card issuer for more information."
  offline_pin_required = "The card has been declined as it requires a PIN."
  online_or_offline_pin_required = "The card has been declined as it requires a PIN."
  pickup_card = "The card cannot be used to make this payment (it is possible it has been reported lost or stolen). Please contact your card issuer for more information."
  pin_try_exceeded = "The allowable number of PIN tries has been exceeded."
  processing_error = "An error occurred while processing the card."
  reenter_transaction = "The payment could not be processed by the issuer for an unknown reason."
  restricted_card = "The card cannot be used to make this payment (it is possible it has been reported lost or stolen). Please contact your card issuer for more information."
  revocation_of_all_authorizations = "The card has been declined for an unknown reason. Please contact your card issuer for more information."
  revocation_of_authorization = "The card has been declined for an unknown reason. Please contact your card issuer for more information."
  security_violation = "The card has been declined for an unknown reason. Please contact your card issuer for more information."
  service_not_allowed = "The card has been declined for an unknown reason. Please contact your card issuer for more information."
  stolen_card = "The payment has been declined because the card is reported stolen."
  stop_payment_order = "The card has been declined for an unknown reason. Please contact your card issuer for more information."
  testmode_decline = "A Stripe test card number was used."
  transaction_not_allowed = "The card has been declined for an unknown reason. Please contact your card issuer for more information."
  try_again_later = "The card has been declined for an unknown reason. Please contact your card issuer for more information."
  withdrawal_count_limit_exceeded = "The customer has exceeded the balance or credit limit available on their card."


class StripeErrorsEs(Enum):
  authentication_required = "La tarjeta ha sido rechazada porque la transacción requiere autentificación."
  approve_with_id = "El pago no se puede autorizar."
  call_issuer = "La tarjeta ha sido rechazada por una razón desconocida. Contacte con el emisor de la tarjeta para más información."
  card_not_supported = "La tarjeta no soporta este tipo de compra."
  card_velocity_exceeded = "El comprador ha excedido el balance o límite de crédito disponible en su tarjeta. Contacte con el emisor de la tarjeta para más información."
  currency_not_supported = "La tarjeta no soporta la divisa especificada."
  do_not_honor = "La tarjeta ha sido rechazada por una razón desconocida. Contacte con el emisor de la tarjeta para más información."
  do_not_try_again = "La tarjeta ha sido rechazada por una razón desconocida. Contacte con el emisor de la tarjeta para más información."
  duplicate_transaction = "Una transacción con importe y tarjeta idénticas fue procesada muy recientemente."
  expired_card = "La tarjeta ha expirado."
  fraudulent = "El pago ha sido rechazado ya que Stripe sospecha que es fraudulento."
  generic_decline = "La tarjeta ha sido rechazada por una razón desconocida. Contacte con el emisor de la tarjeta para más información."
  incorrect_number = "El número de la tarjeta es incorrecto."
  incorrect_cvc = "El numero CVC es incorrecto."
  incorrect_pin = "El PIN introducido es incorrecto."
  incorrect_zip = "El código postal es incorrecto."
  insufficient_funds = "La tarjeta no tiene fondos suficientes para completar la compra."
  invalid_account = "La tarjeta, o la cuenta a la que está asociada, es inválida."
  invalid_amount = "El importe es inválido, o excede el permitido."
  invalid_cvc = "El número CVC es incorrecto."
  invalid_expiry_month = "El mes de caducidad es inválido."
  invalid_expiry_year = "El año de caducidad es inválido."
  invalid_number = "El número de tarjeta es incorrecto."
  invalid_pin = "El PIN introducido es incorrecto."
  issuer_not_available = "El emisor de la tarjeta no pudo ser contactado, por lo que el pago no ha podido ser autorizado."
  lost_card = "El pago ha sido rechazado porque la tarjeta ha sido denunciada como perdida."
  merchant_blacklist = "El pago ha sido rechazado porque coincide con un valor de la lista de bloqueo de Stripe."
  new_account_information_available = "La tarjeta, o cuenta la que está asociada, es inválida. Contacte con el emisor de la tarjeta para más información."
  no_action_taken = "La tarjeta ha sido rechazada por una razón desconocida. Contacte con el emisor de la tarjeta para más información."
  not_permitted = "El pago no está permitido. Contacte con el emisor de la tarjeta para más información."
  offline_pin_required = "La tarjeta ha sido rechazada ya que requiere un PIN."
  online_or_offline_pin_required = "La tarjeta ha sido rechazada ya que requiere un PIN."
  pickup_card = "La tarjeta no se puede usar para realizar este pago (posiblemente haya sido denunciada como robada). Contacte con el emisor de la tarjeta para más información."
  pin_try_exceeded = "Se ha excedido el número máximo de intentos de introducción del PIN."
  processing_error = "Ocurrió un error al procesar la tarjeta."
  reenter_transaction = "El pago no pudo ser procesado por el emisor por una razón desconocida."
  restricted_card = "La tarjeta no se puede usar para realizar este pago (posiblemente haya sido denunciada como perdida o robada). Contacte con el emisor de la tarjeta para más información."
  revocation_of_all_authorizations = "La tarjeta ha sido rechazada por una razón desconocida. Contacte con el emisor de la tarjeta para más información."
  revocation_of_authorization = "La tarjeta ha sido rechazada por una razón desconocida. Contacte con el emisor de la tarjeta para más información."
  security_violation = "La tarjeta ha sido rechazada por una razón desconocida. Contacte con el emisor de la tarjeta para más información."
  service_not_allowed = "La tarjeta ha sido rechazada por una razón desconocida. Contacte con el emisor de la tarjeta para más información."
  stolen_card = "El pago ha sido rechazado porque la tarjeta ha sido denunciada como robada."
  stop_payment_order = "La tarjeta ha sido rechazada por una razón desconocida. Contacte con el emisor de la tarjeta para más información."
  testmode_decline = "Se ha usado una tarjeta de prueba de Stripe."
  transaction_not_allowed = "La tarjeta ha sido rechazada por una razón desconocida. Contacte con el emisor de la tarjeta para más información."
  try_again_later = "La tarjeta ha sido rechazada por una razón desconocida. Contacte con el emisor de la tarjeta para más información."
  withdrawal_count_limit_exceeded = "El comprador ha excedido el balance o límite de crédito disponible en su tarjeta."
