export { default as Billing } from "./Billing";
export { default as EmptyCart } from "./EmptyCart";
export { default as ErrorPayment } from "./ErrorPayment";
export { default as Login } from "./Login";
export { default as NoFavs } from "./NoFavs";
export { default as NoOrders } from "./NoOrders";
export { default as Register } from "./Register";
export { default as Shipping } from "./Shipping";
export { default as Success } from "./Success";
