# Generated by Django 3.1.1 on 2020-09-16 14:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "build_id",
                    models.UUIDField(
                        default=uuid.UUID("684d12ff-8fa9-4ae8-9e98-0188a4be47e5")
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "build_status",
                    models.CharField(
                        choices=[
                            ("STALLED", "Stalled"),
                            ("QUEUED", "Queued"),
                            ("GENERATING", "Generating"),
                            ("UPLOADING", "Uploading"),
                            ("PUBLISHED", "Published"),
                            ("WAITING", "Waiting"),
                        ],
                        default="STALLED",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "preview_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="template_previews/"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Link to Git repository of the template",
                        max_length=150,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreApp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="store_logos/%Y/%m/%d/"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Color in HEX", max_length=7, null=True
                    ),
                ),
                (
                    "api_link",
                    models.CharField(
                        blank=True,
                        help_text="Link to GraphQl API of the store",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stores.template",
                    ),
                ),
            ],
            options={
                "verbose_name": "storeapp",
                "verbose_name_plural": "storeapps",
            },
        ),
    ]
