# Generated by Django 3.1.1 on 2020-09-16 14:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="build_id",
            field=models.UUIDField(
                default=uuid.UUID("296fa765-2cde-4a2f-bd77-bcdc4999ee39")
            ),
        ),
        migrations.AlterField(
            model_name="storeapp",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="template",
                to="stores.template",
            ),
        ),
    ]
