# Generated by Django 3.1.1 on 2020-09-16 14:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stores", "0002_auto_20200916_1649"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="build_id",
            field=models.UUIDField(
                default=uuid.UUID("a06e6848-ba56-4f08-9a4f-396e15f4ac71")
            ),
        ),
        migrations.AlterField(
            model_name="storeapp",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="apps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
