# Generated by Django 3.1.1 on 2020-09-16 14:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_auto_20200916_1650"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="builds",
                to="stores.storeapp",
            ),
        ),
        migrations.AlterField(
            model_name="build",
            name="build_id",
            field=models.UUIDField(
                default=uuid.UUID("cb457cfa-7197-428c-92e2-1066c4ebe9ba")
            ),
        ),
    ]
