# Generated by Django 3.1.1 on 2020-09-16 14:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stores", "0004_auto_20200916_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="builds",
                related_query_name="builds",
                to="stores.storeapp",
            ),
        ),
        migrations.AlterField(
            model_name="build",
            name="build_id",
            field=models.UUIDField(
                default=uuid.UUID("587853ef-d590-4b88-b876-75705cf58a6b")
            ),
        ),
        migrations.AlterField(
            model_name="storeapp",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apps",
                related_query_name="apps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="storeapp",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template",
                related_query_name="template",
                to="stores.template",
            ),
        ),
    ]
