# Generated by Django 3.1.1 on 2020-09-16 15:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stores", "0005_auto_20200916_1656"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeapp",
            name="android_link",
            field=models.CharField(
                blank=True,
                help_text="Link to Goggle Play Store",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storeapp",
            name="ios_link",
            field=models.CharField(
                blank=True, help_text="Link to Apple Store", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="build",
            name="app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="builds",
                to="stores.storeapp",
            ),
        ),
        migrations.AlterField(
            model_name="build",
            name="build_id",
            field=models.UUIDField(
                default=uuid.UUID("665d925d-8df5-45e4-81f3-899733148e52")
            ),
        ),
        migrations.AlterField(
            model_name="storeapp",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="storeapp",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template",
                to="stores.template",
            ),
        ),
    ]
