# Generated by Django 3.1.1 on 2020-09-17 14:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0006_auto_20200916_1727"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="build_id",
            field=models.UUIDField(
                default=uuid.UUID("1cd032d3-d45a-424f-817a-a73ca5dec4b5")
            ),
        ),
    ]
