# Generated by Django 3.1.1 on 2020-09-17 14:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0007_auto_20200917_1623"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="build_id",
            field=models.UUIDField(
                default=uuid.UUID("7aef1074-f62e-478e-a30b-da9ae138e3af")
            ),
        ),
    ]
