# Generated by Django 3.1.2 on 2020-10-19 12:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stores", "0009_auto_20200918_1120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="builds",
                to="stores.storeapp",
            ),
        ),
        migrations.AlterField(
            model_name="build",
            name="build_id",
            field=models.UUIDField(
                default=uuid.UUID("50dc9f11-88c5-46d6-915a-d825ff923763")
            ),
        ),
        migrations.AlterField(
            model_name="storeapp",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="storeapp",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="template",
                to="stores.template",
            ),
        ),
    ]
