# Generated by Django 3.1.2 on 2020-10-19 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0011_auto_20201019_1346"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="build_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
