# Generated by Django 3.1.2 on 2020-11-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0013_storeapp_text_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_test_public", models.CharField(max_length=255)),
                ("stripe_test_secret", models.CharField(max_length=255)),
                ("stripe_prod_public", models.CharField(max_length=255)),
                ("stripe_prod_secret", models.CharField(max_length=255)),
                (
                    "store_app",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_method",
                        to="stores.storeapp",
                    ),
                ),
            ],
        ),
    ]
