# Generated by Django 3.1.3 on 2021-02-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeapp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
