# Generated by Django 3.1.2 on 2021-06-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_auto_20210614_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
