# Generated by Django 3.1.3 on 2021-09-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_auto_20210614_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
