# Generated by Django 3.1.3 on 2021-09-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_template_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='snack',
            field=models.CharField(blank=True, help_text='Expo Snack ID', max_length=150, null=True),
        ),
    ]
