# Generated by Django 3.2.12 on 2022-03-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
