# Generated by Django 3.2 on 2022-06-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_delete_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeapp',
            name='description',
            field=models.CharField(blank=True, help_text='Description to Stores card info', max_length=500, null=True),
        ),
    ]
