# Generated by Django 3.1.1 on 2020-09-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="payment_status",
            new_name="account_status",
        ),
        migrations.AddField(
            model_name="account",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="user_logos/"),
        ),
    ]
